### GET all users
GET http://localhost:3000/api/users HTTP/1.1

### GET a single User
GET http://localhost:3000/api/users/iva94 HTTP/1.1


### GET a single user which doesn't exist
GET http://localhost:3000/api/users/Noel HTTP/1.1

### delete a user 
DELETE http://localhost:3000/api/users/badaba39 HTTP/1.1

### Push all users
POST http://localhost:3000/api/pushUsers HTTP/1.1
Content-Type: application/json


### POST a User
POST http://localhost:3000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "Iva",
    "username": "iva94",
    "password": "123"
}

### Login a user
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "iva94",
    "password": "123"
}

###Login a User
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "iva94",
    "password": "123"
}

### Get logged in user
GET http://localhost:3000/api/me HTTP/1.1